# This workflow will build and draft a new release whenever a new tag is pushed to the repository.
# @authors: Runzhi He <rzhe@pku.edu.cn>
# @date: 2024-01-08

name: Publish Release

on:
  push:
    tags:
      - 'v*'
  # This line enables manual triggering
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Test the setup script
      - name: Install system dependencies
        run: sudo bash scripts/setup/ubuntu_dev.sh

      - name: Setup Conan
        run: pip install conan && conan profile detect

      - name: Install conan dependencies
        run: conan install . -s "build_type=Release" --build=missing

      - name: Build
        run: |
          cmake .. -G Ninja -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
          ninja prepare
          ninja install -v
        working-directory: cmake-build-release

      - name: Create Tarball
        run: |
          ninja -C cmake-build-release tarball
          ninja -C cmake-build-release package

      - name: Sanity Check
        run: |
          bash scripts/init.sh
          (timeout 10s bin/ghttp &) && sleep 3 && bin/gquery -db small -q data/small/small_q0.sql && killall ghttp

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Generate Changelog
        run: |
            npm install -g conventional-changelog-cli
            conventional-changelog -p angular -i CHANGELOG.md -s

      - name: Create a new Release
        uses: ncipollo/release-action@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # https://github.com/ncipollo/release-action for the full list of arguments
          artifacts: gstore-*.tar.gz
          skipIfReleaseExists: true
          draft: true  # generate a draft release
          generateReleaseNotes: false
          bodyFile: CHANGELOG.md
          # generate a pre-release if 'pre', 'rc', or 'beta' is in the tag name, or triggered manually
          prerelease: ${{ github.event_name == 'workflow_dispatch' || contains(github.ref, 'beta') || contains(github.ref, 'rc') || contains(github.ref, 'pre') }}
          # use the tag name if it's a tag, otherwise use the commit hash
          tag: ${{ startsWith(github.ref, 'refs/tags/') && '' || github.sha }}  
